"""add visualizer_type to child_categories

Revision ID: 029b562d4a82
Revises: 0fb98a7c9923
Create Date: 2026-10-05 15:48:38.270384

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '029b562d4a82'
down_revision: Union[str, None] = '0fb98a7c9923'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('child_categories', sa.Column('visualizer_type', sa.String(length=30), nullable=True))
    # ### end Alembic commands ###

    # One-time backfill, mirroring customer_controller.py's old live
    # derivation (name.strip().lower().replace(" ", "_")) exactly — so a
    # category that happened to work today under that derivation keeps
    # working the instant reads switch from "derive live" to "read this
    # column", instead of silently losing its visualizer_type the moment
    # this migration lands. replace() (not regexp_replace) matches Python's
    # str.replace(" ", "_") precisely, including turning a double space
    # into a double underscore rather than collapsing it.
    op.execute(
        """
        UPDATE child_categories
        SET visualizer_type = CASE
            WHEN name ILIKE '%rug%' THEN 'rug'
            WHEN replace(lower(trim(name)), ' ', '_') = 'wall_art' THEN 'wall_art'
            WHEN replace(lower(trim(name)), ' ', '_') = 'wallpaper' THEN 'wallpaper'
            WHEN replace(lower(trim(name)), ' ', '_') = 'wall_paint' THEN 'wall_paint'
            ELSE NULL
        END
        """
    )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('child_categories', 'visualizer_type')
    # ### end Alembic commands ###
