"""add supplier category width to order items

Revision ID: 05a11db98f82
Revises: 31824f99ff90
Create Date: 2026-07-28 15:17:16.956310

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '05a11db98f82'
down_revision: Union[str, None] = '31824f99ff90'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order_items', sa.Column('supplier_name', sa.String(length=250), nullable=True))
    op.add_column('order_items', sa.Column('category_name', sa.String(length=250), nullable=True))
    op.add_column('order_items', sa.Column('width', sa.Numeric(precision=10, scale=2), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('order_items', 'width')
    op.drop_column('order_items', 'category_name')
    op.drop_column('order_items', 'supplier_name')
    # ### end Alembic commands ###
