"""generalize ai credit accounts to supplier or customer owner

Revision ID: 0850e5daee4e
Revises: 958cc8cf1523
Create Date: 2026-08-06 15:35:01.262813

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0850e5daee4e'
down_revision: Union[str, None] = '958cc8cf1523'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ai_credit_transactions', sa.Column('billed_customer_id', sa.UUID(), nullable=True))
    op.create_index('ix_ai_credit_transactions_billed_customer_created', 'ai_credit_transactions', ['billed_customer_id', 'created_at'], unique=False)
    op.create_foreign_key(None, 'ai_credit_transactions', 'customers', ['billed_customer_id'], ['id'], ondelete='CASCADE')
    op.add_column('supplier_ai_credit_batches', sa.Column('customer_id', sa.UUID(), nullable=True))
    op.alter_column('supplier_ai_credit_batches', 'supplier_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.create_index('ix_supplier_ai_credit_batches_customer_date', 'supplier_ai_credit_batches', ['customer_id', 'batch_date'], unique=False)
    op.create_foreign_key(None, 'supplier_ai_credit_batches', 'customers', ['customer_id'], ['id'], ondelete='CASCADE')
    op.add_column('supplier_ai_credit_ledger_entries', sa.Column('customer_id', sa.UUID(), nullable=True))
    op.alter_column('supplier_ai_credit_ledger_entries', 'supplier_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.create_unique_constraint('uq_ai_credit_ledger_customer_period', 'supplier_ai_credit_ledger_entries', ['customer_id', 'period_start'])
    op.create_foreign_key(None, 'supplier_ai_credit_ledger_entries', 'customers', ['customer_id'], ['id'], ondelete='CASCADE')
    op.add_column('supplier_ai_credit_settings', sa.Column('customer_id', sa.UUID(), nullable=True))
    op.alter_column('supplier_ai_credit_settings', 'supplier_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_constraint(op.f('supplier_ai_credit_settings_supplier_id_key'), 'supplier_ai_credit_settings', type_='unique')
    op.create_index('ix_ai_credit_settings_customer_id', 'supplier_ai_credit_settings', ['customer_id'], unique=True, postgresql_where='customer_id IS NOT NULL')
    op.create_index('ix_ai_credit_settings_supplier_id', 'supplier_ai_credit_settings', ['supplier_id'], unique=True, postgresql_where='supplier_id IS NOT NULL')
    op.create_foreign_key(None, 'supplier_ai_credit_settings', 'customers', ['customer_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###

    # CHECK constraints aren't autodetected by autogenerate — added by hand,
    # after all three tables' customer_id columns exist above.
    op.create_check_constraint(
        "ck_ai_credit_settings_exactly_one_owner",
        "supplier_ai_credit_settings",
        "(supplier_id IS NOT NULL) != (customer_id IS NOT NULL)",
    )
    op.create_check_constraint(
        "ck_ai_credit_batches_exactly_one_owner",
        "supplier_ai_credit_batches",
        "(supplier_id IS NOT NULL) != (customer_id IS NOT NULL)",
    )
    op.create_check_constraint(
        "ck_ai_credit_ledger_exactly_one_owner",
        "supplier_ai_credit_ledger_entries",
        "(supplier_id IS NOT NULL) != (customer_id IS NOT NULL)",
    )


def downgrade() -> None:
    op.drop_constraint("ck_ai_credit_ledger_exactly_one_owner", "supplier_ai_credit_ledger_entries", type_="check")
    op.drop_constraint("ck_ai_credit_batches_exactly_one_owner", "supplier_ai_credit_batches", type_="check")
    op.drop_constraint("ck_ai_credit_settings_exactly_one_owner", "supplier_ai_credit_settings", type_="check")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'supplier_ai_credit_settings', type_='foreignkey')
    op.drop_index('ix_ai_credit_settings_supplier_id', table_name='supplier_ai_credit_settings', postgresql_where='supplier_id IS NOT NULL')
    op.drop_index('ix_ai_credit_settings_customer_id', table_name='supplier_ai_credit_settings', postgresql_where='customer_id IS NOT NULL')
    op.create_unique_constraint(op.f('supplier_ai_credit_settings_supplier_id_key'), 'supplier_ai_credit_settings', ['supplier_id'], postgresql_nulls_not_distinct=False)
    op.alter_column('supplier_ai_credit_settings', 'supplier_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_column('supplier_ai_credit_settings', 'customer_id')
    op.drop_constraint(None, 'supplier_ai_credit_ledger_entries', type_='foreignkey')
    op.drop_constraint('uq_ai_credit_ledger_customer_period', 'supplier_ai_credit_ledger_entries', type_='unique')
    op.alter_column('supplier_ai_credit_ledger_entries', 'supplier_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_column('supplier_ai_credit_ledger_entries', 'customer_id')
    op.drop_constraint(None, 'supplier_ai_credit_batches', type_='foreignkey')
    op.drop_index('ix_supplier_ai_credit_batches_customer_date', table_name='supplier_ai_credit_batches')
    op.alter_column('supplier_ai_credit_batches', 'supplier_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_column('supplier_ai_credit_batches', 'customer_id')
    op.drop_constraint(None, 'ai_credit_transactions', type_='foreignkey')
    op.drop_index('ix_ai_credit_transactions_billed_customer_created', table_name='ai_credit_transactions')
    op.drop_column('ai_credit_transactions', 'billed_customer_id')
    # ### end Alembic commands ###
