"""remove status from orders

Revision ID: 0caa73abbab9
Revises: 05a11db98f82
Create Date: 2026-07-28 15:42:29.337728

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0caa73abbab9'
down_revision: Union[str, None] = '05a11db98f82'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'status')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('status', sa.VARCHAR(length=20), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
