"""make product bar_code globally unique

Revision ID: 0fb98a7c9923
Revises: 5877317be4bf
Create Date: 2026-09-08 16:59:41.394007

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0fb98a7c9923'
down_revision: Union[str, None] = '5877317be4bf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_products_bar_code'), table_name='products')
    op.create_index('ux_products_bar_code', 'products', ['bar_code'], unique=True, postgresql_where='deleted_at IS NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ux_products_bar_code', table_name='products', postgresql_where='deleted_at IS NULL')
    op.create_index(op.f('ix_products_bar_code'), 'products', ['bar_code'], unique=False)
    # ### end Alembic commands ###
