"""add_direct_theme_to_customer

Revision ID: 1b9905c44f86
Revises: 4ca78d106a28
Create Date: 2026-08-20 15:07:26.733291

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1b9905c44f86'
down_revision: Union[str, None] = '4ca78d106a28'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customers', sa.Column('primary_color', sa.String(length=20), nullable=True))
    op.add_column('customers', sa.Column('secondary_color', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('customers', 'secondary_color')
    op.drop_column('customers', 'primary_color')
    # ### end Alembic commands ###
