"""add ai credits module tables

Revision ID: 1ed43eafc29e
Revises: 952f632ff9bd
Create Date: 2026-08-05 11:44:07.288808

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1ed43eafc29e'
down_revision: Union[str, None] = '952f632ff9bd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('supplier_ai_credit_batches',
    sa.Column('supplier_id', sa.UUID(), nullable=False),
    sa.Column('batch_date', sa.Date(), nullable=False),
    sa.Column('amount_granted', sa.Integer(), nullable=False),
    sa.Column('amount_remaining', sa.Integer(), nullable=False),
    sa.Column('subscription_year_number', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(length=30), nullable=False),
    sa.Column('note', sa.String(length=500), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['admin_users.id'], ),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_supplier_ai_credit_batches_supplier_date', 'supplier_ai_credit_batches', ['supplier_id', 'batch_date'], unique=False)
    op.create_table('supplier_ai_credit_ledger_entries',
    sa.Column('supplier_id', sa.UUID(), nullable=False),
    sa.Column('period_start', sa.Date(), nullable=False),
    sa.Column('period_end', sa.Date(), nullable=False),
    sa.Column('credits_allocated', sa.Integer(), nullable=False),
    sa.Column('credits_carried_forward', sa.Integer(), nullable=False),
    sa.Column('credits_used_mask_generated', sa.Integer(), nullable=False),
    sa.Column('credits_used_curtain_applied', sa.Integer(), nullable=False),
    sa.Column('credits_purchased', sa.Integer(), nullable=False),
    sa.Column('closing_balance', sa.Integer(), nullable=False),
    sa.Column('credits_lapsed', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('supplier_id', 'period_start', name='uq_ai_credit_ledger_supplier_period')
    )
    op.create_table('supplier_ai_credit_settings',
    sa.Column('supplier_id', sa.UUID(), nullable=False),
    sa.Column('monthly_base_allocation', sa.Integer(), nullable=False),
    sa.Column('tier', sa.String(length=50), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('supplier_id')
    )
    op.create_table('ai_credit_transactions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('supplier_id', sa.UUID(), nullable=True),
    sa.Column('customer_id', sa.UUID(), nullable=True),
    sa.Column('room_id', sa.String(length=250), nullable=True),
    sa.Column('room_category_name', sa.String(length=250), nullable=True),
    sa.Column('is_curtain_room', sa.Boolean(), nullable=False),
    sa.Column('action_type', sa.String(length=30), nullable=False),
    sa.Column('tooltip_element_label', sa.String(length=250), nullable=True),
    sa.Column('product_id', sa.UUID(), nullable=True),
    sa.Column('credits_charged', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_ai_credit_transactions_supplier_created', 'ai_credit_transactions', ['supplier_id', 'created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_ai_credit_transactions_supplier_created', table_name='ai_credit_transactions')
    op.drop_table('ai_credit_transactions')
    op.drop_table('supplier_ai_credit_settings')
    op.drop_table('supplier_ai_credit_ledger_entries')
    op.drop_index('ix_supplier_ai_credit_batches_supplier_date', table_name='supplier_ai_credit_batches')
    op.drop_table('supplier_ai_credit_batches')
    # ### end Alembic commands ###
