"""add soft delete to child categories

Revision ID: 1f50901c55f9
Revises: 21a293f61a6b
Create Date: 2026-07-15 18:11:01.005177

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1f50901c55f9'
down_revision: Union[str, None] = '21a293f61a6b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('child_categories', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('child_categories', 'deleted_at')
    # ### end Alembic commands ###
