"""make product bar_code, shine/fabric transparency, length, width required; quantity/rate optional

Revision ID: 21a293f61a6b
Revises: 67f33b699c50
Create Date: 2026-07-15 12:52:43.308800

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '21a293f61a6b'
down_revision: Union[str, None] = '67f33b699c50'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('products', 'bar_code',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.alter_column('products', 'available_quantity',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('products', 'rate',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               nullable=True)
    op.alter_column('products', 'shine_fabric_value_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('products', 'fabric_transparency_value_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('products', 'length',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               nullable=False)
    op.alter_column('products', 'width',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('products', 'width',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               nullable=True)
    op.alter_column('products', 'length',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               nullable=True)
    op.alter_column('products', 'fabric_transparency_value_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('products', 'shine_fabric_value_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('products', 'rate',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               nullable=False)
    op.alter_column('products', 'available_quantity',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('products', 'bar_code',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    # ### end Alembic commands ###
