"""add soft delete to parent_categories

Revision ID: 278d90ab39ed
Revises: 6ca430518262
Create Date: 2026-07-14 13:29:48.315096

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '278d90ab39ed'
down_revision: Union[str, None] = '6ca430518262'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('parent_categories', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    op.drop_constraint(op.f('parent_categories_name_key'), 'parent_categories', type_='unique')
    op.create_index('ix_parent_categories_name', 'parent_categories', ['name'], unique=True, postgresql_where='deleted_at IS NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_parent_categories_name', table_name='parent_categories', postgresql_where='deleted_at IS NULL')
    op.create_unique_constraint(op.f('parent_categories_name_key'), 'parent_categories', ['name'], postgresql_nulls_not_distinct=False)
    op.drop_column('parent_categories', 'deleted_at')
    # ### end Alembic commands ###
