"""add filters and filter values

Revision ID: 2c5f5772f2d7
Revises: 278d90ab39ed
Create Date: 2026-07-15 10:57:12.831196

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2c5f5772f2d7'
down_revision: Union[str, None] = '278d90ab39ed'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('filters',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_filters_name', 'filters', ['name'], unique=True, postgresql_where='deleted_at IS NULL')
    op.create_table('filter_values',
    sa.Column('filter_id', sa.UUID(), nullable=False),
    sa.Column('child_category_id', sa.UUID(), nullable=False),
    sa.Column('supplier_id', sa.UUID(), nullable=False),
    sa.Column('value', sa.String(length=150), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['child_category_id'], ['child_categories.id'], ),
    sa.ForeignKeyConstraint(['filter_id'], ['filters.id'], ),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_filter_values_child_category_id', 'filter_values', ['child_category_id'], unique=False)
    op.create_index('ix_filter_values_filter_id', 'filter_values', ['filter_id'], unique=False)
    op.create_index('ix_filter_values_supplier_id', 'filter_values', ['supplier_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_filter_values_supplier_id', table_name='filter_values')
    op.drop_index('ix_filter_values_filter_id', table_name='filter_values')
    op.drop_index('ix_filter_values_child_category_id', table_name='filter_values')
    op.drop_table('filter_values')
    op.drop_index('ix_filters_name', table_name='filters', postgresql_where='deleted_at IS NULL')
    op.drop_table('filters')
    # ### end Alembic commands ###
