"""add sub_type to room category image hotspots

Revision ID: 32056034d7be
Revises: f8b1eb88e185
Create Date: 2026-07-27 16:08:40.972174

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '32056034d7be'
down_revision: Union[str, None] = 'f8b1eb88e185'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('room_category_image_hotspots', sa.Column('sub_type', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('room_category_image_hotspots', 'sub_type')
    # ### end Alembic commands ###
