"""add admin user and supplier login events

Revision ID: 42a22c61523d
Revises: 2ad3357b2c86
Create Date: 2026-07-20 16:30:17.460460

"""
import uuid
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '42a22c61523d'
down_revision: Union[str, None] = '2ad3357b2c86'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

# Fixed, not regenerated per run — downgrade() needs to delete this exact row.
LOGIN_HISTORY_MODULE_ID = uuid.UUID("1f3b6a9e-7c2d-4a5e-9b1a-6d2c4e8f0a11")


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin_user_login_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('admin_user_id', sa.UUID(), nullable=False),
    sa.Column('logged_in_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['admin_user_id'], ['admin_users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_admin_user_login_events_admin_user_id_logged_in_at', 'admin_user_login_events', ['admin_user_id', 'logged_in_at'], unique=False)
    op.create_table('supplier_login_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('supplier_id', sa.UUID(), nullable=False),
    sa.Column('logged_in_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_supplier_login_events_supplier_id_logged_in_at', 'supplier_login_events', ['supplier_id', 'logged_in_at'], unique=False)
    # ### end Alembic commands ###

    # New "Login History" leaf under Logs (unified Sub Admin + Supplier login
    # history). Idempotent insert, not a truncate+reseed — safe to run against a
    # database that already has real, granted admin_user_module_permissions rows.
    op.execute(
        sa.text(
            """
            INSERT INTO modules (id, key, name, parent_id, sort_order, is_buildable, is_active, created_at, updated_at)
            SELECT :new_id, :key, :name, m.id, :sort_order, true, true, now(), now()
            FROM modules m WHERE m.key = :parent_key
            ON CONFLICT (key) DO NOTHING
            """
        ).bindparams(
            new_id=LOGIN_HISTORY_MODULE_ID,
            key="logs.login_history",
            name="Login History",
            parent_key="logs",
            sort_order=1000,
        )
    )


def downgrade() -> None:
    op.execute(sa.text("DELETE FROM modules WHERE key = :key").bindparams(key="logs.login_history"))

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_supplier_login_events_supplier_id_logged_in_at', table_name='supplier_login_events')
    op.drop_table('supplier_login_events')
    op.drop_index('ix_admin_user_login_events_admin_user_id_logged_in_at', table_name='admin_user_login_events')
    op.drop_table('admin_user_login_events')
    # ### end Alembic commands ###
