"""make_product_catalog_name_length_width_nullable

Revision ID: 474c43f633d6
Revises: 3864e8170eb1
Create Date: 2026-08-10 12:44:03.770770

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '474c43f633d6'
down_revision: Union[str, None] = '3864e8170eb1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('order_items', 'catalog_name',
               existing_type=sa.VARCHAR(length=250),
               nullable=True)
    op.alter_column('products', 'catalog_name',
               existing_type=sa.VARCHAR(length=250),
               nullable=True)
    op.alter_column('products', 'length',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               nullable=True)
    op.alter_column('products', 'width',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('products', 'width',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               nullable=False)
    op.alter_column('products', 'length',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               nullable=False)
    op.alter_column('products', 'catalog_name',
               existing_type=sa.VARCHAR(length=250),
               nullable=False)
    op.alter_column('order_items', 'catalog_name',
               existing_type=sa.VARCHAR(length=250),
               nullable=False)
    # ### end Alembic commands ###
