"""make product upload log uploaded_by nullable

Revision ID: 4abfda6b8cf8
Revises: 42a22c61523d
Create Date: 2026-07-21 16:52:30.947133

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4abfda6b8cf8'
down_revision: Union[str, None] = '42a22c61523d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('product_upload_logs', 'uploaded_by',
               existing_type=sa.UUID(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('product_upload_logs', 'uploaded_by',
               existing_type=sa.UUID(),
               nullable=False)
    # ### end Alembic commands ###
