"""fix product shine fabric fabric transparency to numeric, add product filter values

Revision ID: 4c22d304fad9
Revises: 57fce7a156d6
Create Date: 2026-07-16 15:37:36.181036

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4c22d304fad9'
down_revision: Union[str, None] = '57fce7a156d6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('product_filter_values',
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.Column('filter_value_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['filter_value_id'], ['filter_values.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('product_id', 'filter_value_id')
    )
    op.add_column('products', sa.Column('shine_fabric', sa.SmallInteger(), nullable=False, server_default='0'))
    op.add_column('products', sa.Column('fabric_transparency', sa.SmallInteger(), nullable=False, server_default='0'))
    op.drop_constraint(op.f('products_fabric_transparency_value_id_fkey'), 'products', type_='foreignkey')
    op.drop_constraint(op.f('products_shine_fabric_value_id_fkey'), 'products', type_='foreignkey')
    op.drop_column('products', 'fabric_transparency_value_id')
    op.drop_column('products', 'shine_fabric_value_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('shine_fabric_value_id', sa.UUID(), autoincrement=False, nullable=False))
    op.add_column('products', sa.Column('fabric_transparency_value_id', sa.UUID(), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('products_shine_fabric_value_id_fkey'), 'products', 'filter_values', ['shine_fabric_value_id'], ['id'])
    op.create_foreign_key(op.f('products_fabric_transparency_value_id_fkey'), 'products', 'filter_values', ['fabric_transparency_value_id'], ['id'])
    op.drop_column('products', 'fabric_transparency')
    op.drop_column('products', 'shine_fabric')
    op.drop_table('product_filter_values')
    # ### end Alembic commands ###
