"""add_profile_image_and_logo_to_supplier_customer

Revision ID: 4ca78d106a28
Revises: d41f816df2ab
Create Date: 2026-08-18 17:44:17.780691

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4ca78d106a28'
down_revision: Union[str, None] = 'd41f816df2ab'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customers', sa.Column('logo_url', sa.String(length=500), nullable=True))
    op.add_column('suppliers', sa.Column('profile_image_url', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('suppliers', 'profile_image_url')
    op.drop_column('customers', 'logo_url')
    # ### end Alembic commands ###
