"""multi-cart: add name/whatsapp_no to carts, drop status singleton

Revision ID: 5877317be4bf
Revises: 1b9905c44f86
Create Date: 2026-09-07 16:36:09.820417

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5877317be4bf'
down_revision: Union[str, None] = '1b9905c44f86'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Existing carts predate the name/whatsapp_no columns and have no valid
    # data for them (they were empty "open" placeholder carts under the old
    # singleton model, never a real named locked cart) - clear them out
    # before adding the NOT NULL columns rather than backfilling fake data.
    # cart_items cascades via its FK's ondelete="CASCADE".
    op.execute("DELETE FROM carts")

    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('carts', sa.Column('name', sa.String(length=250), nullable=False))
    op.add_column('carts', sa.Column('whatsapp_no', sa.String(length=20), nullable=False))
    op.drop_index(op.f('ux_carts_customer_open'), table_name='carts', postgresql_where="((status)::text = 'open'::text)")
    op.create_index('ix_carts_customer_id', 'carts', ['customer_id'], unique=False)
    op.drop_column('carts', 'status')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('carts', sa.Column('status', sa.VARCHAR(length=20), autoincrement=False, nullable=False))
    op.drop_index('ix_carts_customer_id', table_name='carts')
    op.create_index(op.f('ux_carts_customer_open'), 'carts', ['customer_id'], unique=True, postgresql_where="((status)::text = 'open'::text)")
    op.drop_column('carts', 'whatsapp_no')
    op.drop_column('carts', 'name')
    # ### end Alembic commands ###
