"""add products

Revision ID: 67f33b699c50
Revises: 2c5f5772f2d7
Create Date: 2026-07-15 11:13:23.331197

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '67f33b699c50'
down_revision: Union[str, None] = '2c5f5772f2d7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('products',
    sa.Column('child_category_id', sa.UUID(), nullable=False),
    sa.Column('supplier_id', sa.UUID(), nullable=False),
    sa.Column('order_no', sa.Integer(), nullable=False),
    sa.Column('catalog_name', sa.String(length=150), nullable=False),
    sa.Column('design_no', sa.String(length=100), nullable=True),
    sa.Column('bar_code', sa.String(length=100), nullable=True),
    sa.Column('image_url', sa.String(length=500), nullable=True),
    sa.Column('available_quantity', sa.Integer(), nullable=False),
    sa.Column('rate', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('shine_fabric_value_id', sa.UUID(), nullable=True),
    sa.Column('fabric_transparency_value_id', sa.UUID(), nullable=True),
    sa.Column('length', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('width', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['child_category_id'], ['child_categories.id'], ),
    sa.ForeignKeyConstraint(['fabric_transparency_value_id'], ['filter_values.id'], ),
    sa.ForeignKeyConstraint(['shine_fabric_value_id'], ['filter_values.id'], ),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_products_bar_code', 'products', ['bar_code'], unique=False)
    op.create_index('ix_products_child_category_id', 'products', ['child_category_id'], unique=False)
    op.create_index('ix_products_is_active', 'products', ['is_active'], unique=False)
    op.create_index('ix_products_supplier_id', 'products', ['supplier_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_products_supplier_id', table_name='products')
    op.drop_index('ix_products_is_active', table_name='products')
    op.drop_index('ix_products_child_category_id', table_name='products')
    op.drop_index('ix_products_bar_code', table_name='products')
    op.drop_table('products')
    # ### end Alembic commands ###
