"""add customer_login_events

Revision ID: 6ca430518262
Revises: bfcecc370c73
Create Date: 2026-07-14 11:19:44.966426

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6ca430518262'
down_revision: Union[str, None] = 'bfcecc370c73'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customer_login_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('customer_id', sa.UUID(), nullable=False),
    sa.Column('logged_in_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_customer_login_events_customer_id_logged_in_at', 'customer_login_events', ['customer_id', 'logged_in_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_customer_login_events_customer_id_logged_in_at', table_name='customer_login_events')
    op.drop_table('customer_login_events')
    # ### end Alembic commands ###
