"""per-hotspot product on qr catalogue entries

Revision ID: 79ed5fb3d0d1
Revises: aca9d308d671
Create Date: 2026-07-30 17:04:37.357272

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '79ed5fb3d0d1'
down_revision: Union[str, None] = 'aca9d308d671'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('qr_catalogue_entries_product_id_fkey'), 'qr_catalogue_entries', type_='foreignkey')
    op.drop_column('qr_catalogue_entries', 'product_id')
    op.add_column('qr_catalogue_entry_hotspots', sa.Column('product_id', sa.UUID(), nullable=False))
    op.create_foreign_key(None, 'qr_catalogue_entry_hotspots', 'products', ['product_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'qr_catalogue_entry_hotspots', type_='foreignkey')
    op.drop_column('qr_catalogue_entry_hotspots', 'product_id')
    op.add_column('qr_catalogue_entries', sa.Column('product_id', sa.UUID(), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('qr_catalogue_entries_product_id_fkey'), 'qr_catalogue_entries', 'products', ['product_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###
