"""add supplier customer identity link

Revision ID: 88c126524c55
Revises: 1ed43eafc29e
Create Date: 2026-08-05 16:17:01.038600

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '88c126524c55'
down_revision: Union[str, None] = '1ed43eafc29e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customers', sa.Column('linked_supplier_id', sa.UUID(), nullable=True))
    op.create_index('ix_customers_linked_supplier_id', 'customers', ['linked_supplier_id'], unique=True)
    op.create_foreign_key(None, 'customers', 'suppliers', ['linked_supplier_id'], ['id'])
    op.add_column('suppliers', sa.Column('linked_customer_id', sa.UUID(), nullable=True))
    op.create_index('ix_suppliers_linked_customer_id', 'suppliers', ['linked_customer_id'], unique=True)
    op.create_foreign_key(None, 'suppliers', 'customers', ['linked_customer_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'suppliers', type_='foreignkey')
    op.drop_index('ix_suppliers_linked_customer_id', table_name='suppliers')
    op.drop_column('suppliers', 'linked_customer_id')
    op.drop_constraint(None, 'customers', type_='foreignkey')
    op.drop_index('ix_customers_linked_supplier_id', table_name='customers')
    op.drop_column('customers', 'linked_supplier_id')
    # ### end Alembic commands ###
