"""add room category images

Revision ID: 904ebd3f99f0
Revises: e66e85622f81
Create Date: 2026-07-20 15:37:44.959914

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '904ebd3f99f0'
down_revision: Union[str, None] = 'e66e85622f81'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('room_category_images',
    sa.Column('room_category_id', sa.UUID(), nullable=False),
    sa.Column('order_no', sa.Integer(), nullable=False),
    sa.Column('image_url', sa.String(length=500), nullable=False),
    sa.Column('is_uploaded_to_cdn', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['room_category_id'], ['room_categories.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('room_category_image_suppliers',
    sa.Column('room_category_image_id', sa.UUID(), nullable=False),
    sa.Column('supplier_id', sa.UUID(), nullable=False),
    sa.Column('mapped_by', sa.UUID(), nullable=True),
    sa.Column('mapped_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['mapped_by'], ['admin_users.id'], ),
    sa.ForeignKeyConstraint(['room_category_image_id'], ['room_category_images.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('room_category_image_id', 'supplier_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('room_category_image_suppliers')
    op.drop_table('room_category_images')
    # ### end Alembic commands ###
