"""add_secondary_color_to_supplier_customer_themes

Revision ID: 952f632ff9bd
Revises: b3bd95bddd6d
Create Date: 2026-08-03 12:54:29.986874

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '952f632ff9bd'
down_revision: Union[str, None] = 'b3bd95bddd6d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('supplier_customer_themes', sa.Column('secondary_color', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('supplier_customer_themes', 'secondary_color')
    # ### end Alembic commands ###
