"""product upload logs

Revision ID: a979fcc02c3d
Revises: 4c22d304fad9
Create Date: 2026-07-17 11:33:58.225569

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a979fcc02c3d'
down_revision: Union[str, None] = '4c22d304fad9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('product_upload_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('supplier_id', sa.UUID(), nullable=False),
    sa.Column('uploaded_by', sa.UUID(), nullable=False),
    sa.Column('file_name', sa.String(length=255), nullable=False),
    sa.Column('total_rows', sa.Integer(), nullable=False),
    sa.Column('success_count', sa.Integer(), nullable=False),
    sa.Column('error_count', sa.Integer(), nullable=False),
    sa.Column('is_synced', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.id'], ),
    sa.ForeignKeyConstraint(['uploaded_by'], ['admin_users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_product_upload_logs_supplier_id', 'product_upload_logs', ['supplier_id'], unique=False)
    op.create_table('product_upload_log_items',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('log_id', sa.UUID(), nullable=False),
    sa.Column('row_no', sa.Integer(), nullable=False),
    sa.Column('catalog_name', sa.String(length=250), nullable=True),
    sa.Column('is_success', sa.Boolean(), nullable=False),
    sa.Column('message', sa.String(length=1000), nullable=True),
    sa.ForeignKeyConstraint(['log_id'], ['product_upload_logs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_product_upload_log_items_log_id', 'product_upload_log_items', ['log_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_product_upload_log_items_log_id', table_name='product_upload_log_items')
    op.drop_table('product_upload_log_items')
    op.drop_index('ix_product_upload_logs_supplier_id', table_name='product_upload_logs')
    op.drop_table('product_upload_logs')
    # ### end Alembic commands ###
