"""add customer refresh tokens and visualizer usage tracking tables

Revision ID: ae45a9526619
Revises: 15a239dcf546
Create Date: 2026-07-27 11:03:54.279572

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ae45a9526619'
down_revision: Union[str, None] = '15a239dcf546'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customer_refresh_tokens',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('customer_id', sa.UUID(), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('issued_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token_hash')
    )
    op.create_index('ix_customer_refresh_tokens_customer_id', 'customer_refresh_tokens', ['customer_id'], unique=False)
    op.create_table('tooltip_usages',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('customer_id', sa.UUID(), nullable=False),
    sa.Column('room_id', sa.String(length=255), nullable=False),
    sa.Column('hotspot_id', sa.String(length=255), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('room_id', 'hotspot_id', 'customer_id', name='uq_tooltip_usages_room_hotspot_customer')
    )
    op.create_index('ix_tooltip_usages_customer_id', 'tooltip_usages', ['customer_id'], unique=False)
    op.create_table('usage_logs',
    sa.Column('customer_id', sa.UUID(), nullable=False),
    sa.Column('room_id', sa.String(length=255), nullable=True),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('curtain_style', sa.String(length=100), nullable=True),
    sa.Column('input_tokens', sa.Integer(), nullable=False),
    sa.Column('output_tokens', sa.Integer(), nullable=False),
    sa.Column('total_tokens', sa.Integer(), nullable=False),
    sa.Column('openai_status', sa.String(length=20), nullable=True),
    sa.Column('segmentation_status', sa.String(length=20), nullable=True),
    sa.Column('generation_units', sa.Integer(), nullable=False),
    sa.Column('tooltip_units', sa.Integer(), nullable=False),
    sa.Column('error', sa.String(length=2000), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('room_id', 'customer_id', name='uq_usage_logs_room_customer')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('usage_logs')
    op.drop_index('ix_tooltip_usages_customer_id', table_name='tooltip_usages')
    op.drop_table('tooltip_usages')
    op.drop_index('ix_customer_refresh_tokens_customer_id', table_name='customer_refresh_tokens')
    op.drop_table('customer_refresh_tokens')
    # ### end Alembic commands ###
