"""add action to product upload log items

Revision ID: b320d0ac9533
Revises: a979fcc02c3d
Create Date: 2026-07-17 12:58:57.286505

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b320d0ac9533'
down_revision: Union[str, None] = 'a979fcc02c3d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product_upload_log_items', sa.Column('action', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('product_upload_log_items', 'action')
    # ### end Alembic commands ###
