"""add categories, customers, suppliers modules

Revision ID: bfcecc370c73
Revises: 143f9468a10b
Create Date: 2026-07-13 14:12:44.621413

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bfcecc370c73'
down_revision: Union[str, None] = '143f9468a10b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('parent_categories',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('icon_url', sa.String(length=500), nullable=True),
    sa.Column('sort_order', sa.SmallInteger(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('child_categories',
    sa.Column('parent_category_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('icon_url', sa.String(length=500), nullable=True),
    sa.Column('sort_order', sa.SmallInteger(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['parent_category_id'], ['parent_categories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_child_categories_parent_category_id', 'child_categories', ['parent_category_id'], unique=False)
    op.create_table('customers',
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('date_of_start', sa.Date(), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('phone_number', sa.String(length=20), nullable=False),
    sa.Column('gst_number', sa.String(length=20), nullable=True),
    sa.Column('address', sa.String(length=255), nullable=True),
    sa.Column('pin_code', sa.String(length=10), nullable=True),
    sa.Column('state_code', sa.String(length=10), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('profile_image_url', sa.String(length=500), nullable=True),
    sa.Column('device_limit', sa.SmallInteger(), nullable=False),
    sa.Column('active_device_count', sa.SmallInteger(), nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('customer_code', sa.String(length=100), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['admin_users.id'], ),
    sa.ForeignKeyConstraint(['state_code'], ['states.code'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_customers_customer_code', 'customers', ['customer_code'], unique=True, postgresql_where='deleted_at IS NULL')
    op.create_index('ix_customers_email', 'customers', ['email'], unique=True, postgresql_where='deleted_at IS NULL')
    op.create_index('ix_customers_is_active', 'customers', ['is_active'], unique=False)
    op.create_index('ix_customers_phone_number', 'customers', ['phone_number'], unique=True, postgresql_where='deleted_at IS NULL')
    op.create_index('ix_customers_state_code', 'customers', ['state_code'], unique=False)
    op.create_table('suppliers',
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('start_of_subscription', sa.Date(), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('phone_number', sa.String(length=20), nullable=False),
    sa.Column('gst_number', sa.String(length=20), nullable=True),
    sa.Column('address', sa.String(length=255), nullable=True),
    sa.Column('pin_code', sa.String(length=10), nullable=True),
    sa.Column('state_code', sa.String(length=10), nullable=False),
    sa.Column('city', sa.String(length=100), nullable=False),
    sa.Column('web_link', sa.String(length=500), nullable=True),
    sa.Column('logo_url', sa.String(length=500), nullable=True),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['admin_users.id'], ),
    sa.ForeignKeyConstraint(['state_code'], ['states.code'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_suppliers_is_active', 'suppliers', ['is_active'], unique=False)
    op.create_index('ix_suppliers_phone_number', 'suppliers', ['phone_number'], unique=True, postgresql_where='deleted_at IS NULL')
    op.create_index('ix_suppliers_state_code', 'suppliers', ['state_code'], unique=False)
    op.create_index('ix_suppliers_username', 'suppliers', ['username'], unique=True, postgresql_where='deleted_at IS NULL')
    op.create_table('customer_suppliers',
    sa.Column('customer_id', sa.UUID(), nullable=False),
    sa.Column('supplier_id', sa.UUID(), nullable=False),
    sa.Column('mapped_by', sa.UUID(), nullable=True),
    sa.Column('mapped_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['mapped_by'], ['admin_users.id'], ),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('customer_id', 'supplier_id')
    )
    op.create_table('supplier_child_categories',
    sa.Column('supplier_id', sa.UUID(), nullable=False),
    sa.Column('child_category_id', sa.UUID(), nullable=False),
    sa.Column('granted_by', sa.UUID(), nullable=True),
    sa.Column('granted_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['child_category_id'], ['child_categories.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['granted_by'], ['admin_users.id'], ),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('supplier_id', 'child_category_id')
    )
    op.create_table('supplier_module_permissions',
    sa.Column('supplier_id', sa.UUID(), nullable=False),
    sa.Column('module_id', sa.UUID(), nullable=False),
    sa.Column('granted_by', sa.UUID(), nullable=True),
    sa.Column('granted_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['granted_by'], ['admin_users.id'], ),
    sa.ForeignKeyConstraint(['module_id'], ['modules.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('supplier_id', 'module_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('supplier_module_permissions')
    op.drop_table('supplier_child_categories')
    op.drop_table('customer_suppliers')
    op.drop_index('ix_suppliers_username', table_name='suppliers', postgresql_where='deleted_at IS NULL')
    op.drop_index('ix_suppliers_state_code', table_name='suppliers')
    op.drop_index('ix_suppliers_phone_number', table_name='suppliers', postgresql_where='deleted_at IS NULL')
    op.drop_index('ix_suppliers_is_active', table_name='suppliers')
    op.drop_table('suppliers')
    op.drop_index('ix_customers_state_code', table_name='customers')
    op.drop_index('ix_customers_phone_number', table_name='customers', postgresql_where='deleted_at IS NULL')
    op.drop_index('ix_customers_is_active', table_name='customers')
    op.drop_index('ix_customers_email', table_name='customers', postgresql_where='deleted_at IS NULL')
    op.drop_index('ix_customers_customer_code', table_name='customers', postgresql_where='deleted_at IS NULL')
    op.drop_table('customers')
    op.drop_index('ix_child_categories_parent_category_id', table_name='child_categories')
    op.drop_table('child_categories')
    op.drop_table('parent_categories')
    # ### end Alembic commands ###
