"""remove width height from room category image hotspots

Revision ID: e055966b90d2
Revises: 0caa73abbab9
Create Date: 2026-07-28 16:30:44.820130

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e055966b90d2'
down_revision: Union[str, None] = '0caa73abbab9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('room_category_image_hotspots', 'height')
    op.drop_column('room_category_image_hotspots', 'width')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('room_category_image_hotspots', sa.Column('width', sa.NUMERIC(precision=6, scale=4), autoincrement=False, nullable=False))
    op.add_column('room_category_image_hotspots', sa.Column('height', sa.NUMERIC(precision=6, scale=4), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
