"""add qr catalogue entries

Revision ID: e2ca5400d014
Revises: e055966b90d2
Create Date: 2026-07-29 14:37:41.708694

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e2ca5400d014'
down_revision: Union[str, None] = 'e055966b90d2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('qr_catalogue_entries',
    sa.Column('customer_id', sa.UUID(), nullable=False),
    sa.Column('filter_value', sa.String(length=250), nullable=False),
    sa.Column('catalog_name', sa.String(length=250), nullable=False),
    sa.Column('room_category_image_id', sa.UUID(), nullable=False),
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['room_category_image_id'], ['room_category_images.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('customer_id', 'filter_value', name='uq_qr_catalogue_entry_customer_filter')
    )
    op.create_table('qr_catalogue_entry_hotspots',
    sa.Column('qr_catalogue_entry_id', sa.UUID(), nullable=False),
    sa.Column('hotspot_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['hotspot_id'], ['room_category_image_hotspots.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['qr_catalogue_entry_id'], ['qr_catalogue_entries.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('qr_catalogue_entry_id', 'hotspot_id')
    )
    op.create_index('ix_qr_catalogue_entry_hotspots_entry_id', 'qr_catalogue_entry_hotspots', ['qr_catalogue_entry_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_qr_catalogue_entry_hotspots_entry_id', table_name='qr_catalogue_entry_hotspots')
    op.drop_table('qr_catalogue_entry_hotspots')
    op.drop_table('qr_catalogue_entries')
    # ### end Alembic commands ###
