"""remove shine fabric and fabric transparency from products

Revision ID: e66e85622f81
Revises: ca3e8286086e
Create Date: 2026-07-20 11:46:23.190903

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e66e85622f81'
down_revision: Union[str, None] = 'ca3e8286086e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'fabric_transparency')
    op.drop_column('products', 'shine_fabric')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('shine_fabric', sa.SMALLINT(), server_default=sa.text("'0'::smallint"), autoincrement=False, nullable=False))
    op.add_column('products', sa.Column('fabric_transparency', sa.SMALLINT(), server_default=sa.text("'0'::smallint"), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
