"""add room category image hotspots

Revision ID: f8b1eb88e185
Revises: ae45a9526619
Create Date: 2026-07-27 15:43:31.921056

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f8b1eb88e185'
down_revision: Union[str, None] = 'ae45a9526619'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('room_category_image_hotspots',
    sa.Column('room_category_image_id', sa.UUID(), nullable=False),
    sa.Column('label', sa.String(length=250), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('options', sa.String(length=500), nullable=True),
    sa.Column('confidence', sa.Numeric(precision=4, scale=3), nullable=True),
    sa.Column('description', sa.String(length=1000), nullable=True),
    sa.Column('mask_image_url', sa.String(length=500), nullable=False),
    sa.Column('is_uploaded_to_cdn', sa.Boolean(), nullable=False),
    sa.Column('x', sa.Numeric(precision=6, scale=4), nullable=False),
    sa.Column('y', sa.Numeric(precision=6, scale=4), nullable=False),
    sa.Column('width', sa.Numeric(precision=6, scale=4), nullable=False),
    sa.Column('height', sa.Numeric(precision=6, scale=4), nullable=False),
    sa.Column('order_no', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['room_category_image_id'], ['room_category_images.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_room_category_image_hotspots_image_id', 'room_category_image_hotspots', ['room_category_image_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_room_category_image_hotspots_image_id', table_name='room_category_image_hotspots')
    op.drop_table('room_category_image_hotspots')
    # ### end Alembic commands ###
